# Generated by Django 5.2.13 on 2026-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("preferred_categories", models.JSONField(blank=True, default=list)),
                (
                    "preferred_raw_categories",
                    models.JSONField(blank=True, default=list),
                ),
                ("home_city", models.CharField(default="Кишинёв", max_length=128)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ru", "Русский"),
                            ("ro", "Română"),
                        ],
                        default="ru",
                        max_length=2,
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("free_only", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("event_id", models.CharField(db_index=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("click", "Click"),
                            ("save", "Save"),
                            ("ticket_click", "Ticket click"),
                            ("dismiss", "Dismiss"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Interaction",
                "verbose_name_plural": "Interactions",
                "db_table": "interactions",
                "indexes": [
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="interaction_user_id_beb693_idx",
                    ),
                    models.Index(
                        fields=["event_id", "kind"],
                        name="interaction_event_i_e92cfc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("event_id", models.CharField(db_index=True, max_length=64)),
                ("rank", models.PositiveSmallIntegerField()),
                ("score", models.FloatField()),
                ("feature_breakdown", models.JSONField(blank=True, default=dict)),
                ("served_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Recommendation log",
                "verbose_name_plural": "Recommendation logs",
                "db_table": "recommendation_logs",
                "indexes": [
                    models.Index(
                        fields=["user_id", "served_at"],
                        name="recommendat_user_id_18b92d_idx",
                    )
                ],
            },
        ),
    ]
