# Generated by Django 5.2.13 on 2026-05-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tg_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('preferred_categories', models.JSONField(blank=True, default=list)),
                ('preferred_raw_categories', models.JSONField(blank=True, default=list)),
                ('home_city', models.CharField(default='Кишинёв', max_length=128)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('ro', 'Română')], default='ru', max_length=2)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('event_id', models.BigIntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('save', 'Save'), ('ticket_click', 'Ticket click'), ('dismiss', 'Dismiss')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'db_table': 'interactions',
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='interaction_user_id_beb693_idx'), models.Index(fields=['event_id', 'kind'], name='interaction_event_i_e92cfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('event_id', models.BigIntegerField(db_index=True)),
                ('is_new', models.BooleanField(default=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.FloatField()),
                ('feature_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendations',
                'indexes': [models.Index(fields=['user_id', 'is_new'], name='rec_user_new_idx'), models.Index(fields=['user_id', 'created_at'], name='rec_user_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'event_id'), name='recommendation_unique_user_event_id')],
            },
        ),
    ]
